<a href="https://colab.research.google.com/github/techbhuvi04/Data-Science-2026/blob/main/Numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(1,120,15)

In [ ]:
e = np.array([1,1,2,2,3,4,4,4,5,5,6,6,7,8,8,8,9,9,9,10])

In [ ]:
np.unique(e)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Expand Dims

In [ ]:
a

array([119, 113, 110,  23,  38,  61,  25,  81,  74, 113,  61,  85,  94,
        37,  77])

In [ ]:
np.expand_dims(a,axis=1)

array([[119],
       [113],
       [110],
       [ 23],
       [ 38],
       [ 61],
       [ 25],
       [ 81],
       [ 74],
       [113],
       [ 61],
       [ 85],
       [ 94],
       [ 37],
       [ 77]])

# np.where

In [ ]:
a

array([119, 113, 110,  23,  38,  61,  25,  81,  74, 113,  61,  85,  94,
        37,  77])

In [ ]:
a[(a>50)]

array([119, 113, 110,  61,  81,  74, 113,  61,  85,  94,  77])

In [ ]:
np.where(a>50)

(array([ 0,  1,  2,  5,  7,  8,  9, 10, 11, 12, 14]),)

In [ ]:
np.where(a>50,0,a)

array([ 0,  0,  0, 23, 38,  0, 25,  0,  0,  0,  0,  0,  0, 37,  0])

In [ ]:
np.where(a%2==0,0,a)

array([119, 113,   0,  23,   0,  61,  25,  81,   0, 113,  61,  85,   0,
        37,  77])

# *np.argumax*

In [ ]:
a

array([119, 113, 110,  23,  38,  61,  25,  81,  74, 113,  61,  85,  94,
        37,  77])

In [ ]:
np.argmax(a)

np.int64(0)

# np.argmin

In [ ]:
np.argmin(a)

np.int64(3)

# np.cumsum

In [ ]:
a

array([119, 113, 110,  23,  38,  61,  25,  81,  74, 113,  61,  85,  94,
        37,  77])

In [ ]:
np.cumsum(a)

array([ 119,  232,  342,  365,  403,  464,  489,  570,  644,  757,  818,
        903,  997, 1034, 1111])

In [ ]:
np.median(a)

np.float64(77.0)

# np.corrcoef

In [ ]:
salary = np.array([20000,40000,30000,35000,50000])
experience = np.array([1,3,2,4,2])

#


In [ ]:
a

array([119, 113, 110,  23,  38,  61,  25,  81,  74, 113,  61,  85,  94,
        37,  77])

In [ ]:
items = [10,20,30,40,50,60]
a[np.isin(a,items)]

array([], dtype=int64)

# np.flip

In [ ]:
a

array([119, 113, 110,  23,  38,  61,  25,  81,  74, 113,  61,  85,  94,
        37,  77])

In [ ]:
np.flip(a)

array([ 77,  37,  94,  85,  61, 113,  74,  81,  25,  61,  38,  23, 110,
       113, 119])

# np.put

In [ ]:
a

array([119, 113, 110,  23,  38,  61,  25,  81,  74, 113,  61,  85,  94,
        37,  77])

In [ ]:
np.put(a,[0,1],[110,530])

# Delete

In [ ]:
a

array([110, 530, 110,  23,  38,  61,  25,  81,  74, 113,  61,  85,  94,
        37,  77])

In [ ]:
#np.delete(a,3)
np.delete(a,5)

array([110, 530, 110,  23,  38,  25,  81,  74, 113,  61,  85,  94,  37,
        77])

# Set Function
* np.union1d
* np.intersect1d
* np.setdiff1d
* np.setxor1d
* np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.in1d(m,1)

/tmp/ipython-input-3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

# np.clip

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 38, 61, 25, 75, 74, 75, 61, 75, 75, 37, 75])

In [ ]:
jj